spring:
  application:
    name: accident-factory
  
  datasource:
    url: jdbc:mysql://localhost:3306/accident_factory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

logging:
  level:
    com.kakaomap.accidentfactory: DEBUG
    org.springframework.security: DEBUG

